### ISSUE TITLE
Add graphiql tool

### ISSUE THREAD

**Issue by lecovich** [wgOpenSource/gqclans-falcon#4]
Add graphiql tool (https://github.com/graphql/graphiql)

**Comment by frsv** [comment]
My suggestion is to create a pypi package which will provide a resource with graphiql console out of the box. E.g. https://github.com/graphql-python/flask-graphql

There are some reasons why it makes sense:
1. There is no completed solution with graphiql console for Falcon. Such package would be a great contribution in OSS and potentially will be really useful (flask-graphql has more than 300 stars)
2. It's not a good approach to place assets files in project, as it complicates the upgrade of the console and kills versioning.

**Comment by lecovich** [comment]
@frsv great idea! But it could take some extra time to place a contribution package at  https://github.com/graphql-python. From my side I will start this activity. Until contribution package would be ready I propose to use static assets.

**Comment by lecovich** [comment]
Pull request #5 was merged,
related issue #6 was created.
